hr_search_engine/urls.py
# -*- coding:utf-8 -*-
"""
@author:TANYIPENG631
@file: urls.py
@time: 2018/12/6  16:53
"""
from django.urls import path

from . import views

app_name = 'hr_search_engine'
urlpatterns = [
    path('naive/', views.naive, name='naive'),
    path('categories/', views.categories, name='categories'),
    path('custom/', views.custom, name='custom'),
    path('query_recommend/', views.query_recommend, name='query_recommend'),
    path('es/esquery', views.esquery, name='esquery'),
]

search_engine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('search/', include('hr_search_engine.urls')),
    path('admin/', admin.site.urls),
]

hr_search_engine/models.py
from django.db import models


class Products(models.Model):
    code = models.CharField(max_length=30)

    def _get_full_name(self):  # 注意此处，很重要，通过加入full_name这一属性，完成了与JS的数据对接
        return self.name

    full_name = property(_get_full_name)

hr_search_engine/views.py
import os
import json
import pickle

from django.http import HttpResponse
from django.shortcuts import render

APP_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(APP_DIR, 'static')
TOP_N = 8
DAT_CACHE = 'keywords_trie.pickle'

#现在把词库初始化放在这里为了方便
from .before_runserver import main
main()
keyword_dat = pickle.load(open(os.path.join(STATIC_DIR, DAT_CACHE), 'rb'))


def naive(request):
    userdic = ['ActionScript','AppleScript','Asp','BASIC','C','C++','Clojure','COBOL','ColdFusion','Erlang','Fortran','Groovy','Haskell','Java','JavaScript','Lisp','Perl','PHP','Python','Ruby','Scala','Scheme']
    return render(request, 'hr_search_engine/search.html', {'availableTags': json.dumps(userdic)})


def categories(request):
    return render(request, 'hr_search_engine/categories.html')


def custom(request):
    return render(request, 'hr_search_engine/ajax_search.html')


def query_recommend(request):
    if 'term' in request.GET:
        q_str = request.GET['term']
        if isinstance(q_str, str):
            # 这里是查询并返回联想词的逻辑
            q = q_str.split(' ')[-1]
            _q = ' '.join(q_str.split(' ')[:-1])
            candidates = auto_complete(q)
            print(candidates)
            output = []
            keyword_set = []
            for can in candidates:
                if can['v'] in keyword_set:
                    continue
                else:
                    keyword_set.append(can['v'])
            for kw in keyword_set:
                output.append(_q + ' ' + kw)
            return HttpResponse(json.dumps(output), 'application/json')

    return HttpResponse()


def auto_complete(word):
    candidates = list()
    for candidate in keyword_dat.items(word):
        for word in candidate[1]:
            candidates.append(word)
    rs = sorted(candidates, key=lambda x: x['w'], reverse=True)[:TOP_N]
    return rs


def esquery(request):
    if 'query' in request.GET:
        q_str = request.GET['query']
        return HttpResponse(json.dumps(q_str), 'application/json')
    return HttpResponse()


if __name__ == '__main__':
    print(auto_complete('小'))

hr_search_engine/templates/hr_search_engine/ajax_search.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Autocomplete - Remote JSONP datasource</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#query" ).autocomplete({
        source: "{% url 'hr_search_engine:query_recommend' %}",
    } );

  } );
  </script>
</head>
<body>
<h2>智能搜索引擎 V1.0 测试 - Custom</h2>
<br/>
<div class="ui-widget">
    <form action="{% url 'hr_search_engine:esquery' %}" method="GET">
  <label for="query">请输入搜索语句: </label>
  <input id="query", name="query">
    <input type="submit" value="查询" id="esquery">
    </form>
</div>
</body>
</html>

hr_search_engine/templates/hr_search_engine/categories.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Autocomplete - Categories</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <style>
  .ui-autocomplete-category {
    font-weight: bold;
    padding: .2em .4em;
    margin: .8em 0 .2em;
    line-height: 1.5;
  }
  </style>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $.widget( "custom.catcomplete", $.ui.autocomplete, {
      _create: function() {
        this._super();
        this.widget().menu( "option", "items", "> :not(.ui-autocomplete-category)" );
      },
      _renderMenu: function( ul, items ) {
        var that = this,
          currentCategory = "";
        $.each( items, function( index, item ) {
          var li;
          if ( item.category != currentCategory ) {
            ul.append( "<li class='ui-autocomplete-category'>" + item.category + "</li>" );
            currentCategory = item.category;
          }
          li = that._renderItemData( ul, item );
          if ( item.category ) {
            li.attr( "aria-label", item.category + " : " + item.label );
          }
        });
      }
    });
    var data = [
      { label: "anders", category: "" },
      { label: "andreas", category: "" },
      { label: "antal", category: "" },
      { label: "annhhx10", category: "Products" },
      { label: "annk K12", category: "Products" },
      { label: "annttop C13", category: "Products" },
      { label: "anders andersson", category: "People" },
      { label: "andreas andersson", category: "People" },
      { label: "andreas johnson", category: "People" }
    ];

    $( "#search" ).catcomplete({
      delay: 0,
      source: data
    });
  } );
  </script>
</head>
<body>
<h2>智能搜索引擎 V1.0 测试 - Categories</h2>

<div class="ui-widget">
  <label for="search">请输入搜索语句: </label>
  <input id="search">
</div>


</body>
</html>

hr_search_engine/templates/hr_search_engine/search.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Autocomplete - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
      var userDict = {{ availableTags|safe }};
  $( function() {
    $( "#tags" ).autocomplete({
      source: userDict
    });
  } );
  </script>
</head>
<body>
<h2>智能搜索引擎 V1.0 测试 - Naive</h2>
<div class="ui-widget">
  <label for="tags">请输入搜索语句: </label>
  <input id="tags">
</div>


</body>
</html>